spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

loans:
  message: "Hi"
  contactDetails:
    name: "Mehrad PROD"
    email: "mehrad@fakeemail.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267