services:
  configserver:
    image: "iamehraad/configserver:0.2"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"\
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank

  accounts:
    image: "iamehraad/accounts:0.2"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default

  loans:
    image: "iamehraad/loans:0.2"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default

  cards:
    image: "iamehraad/cards:0.2"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default

networks:
  easybank:
    driver: "bridge"
